version: "3"

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    container_name: nc_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ~/.private/db.env

  app:
    build: .
    container_name: nc_app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - TRUSTED_PROXIES='192.168.0.0/16'
      - NEXTCLOUD_TRUSTED_DOMAINS=<host_ip>
      - OVERWRITEPROTOCOL=https
    env_file:
      - ~/.private/db.env
    depends_on:
      - db

  caddy:
    image: caddy
    container_name: nc_caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/log/caddy:/var/log/caddy
      - ~/.private:/etc/ssl/private
    ports:
      - "443:443"
    restart: always
    depends_on:
      - db
      - app
